# Generated by Django 5.2.7 on 2025-10-09 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название книги', max_length=100, verbose_name='books_name')),
                ('date_pub', models.DateTimeField(auto_now_add=True, help_text='Укажите дату и время публикации', verbose_name='books_date_pub')),
                ('genre', models.ForeignKey(help_text='Выберите название жанра', on_delete=django.db.models.deletion.PROTECT, to='genre.genre', verbose_name='books_genre')),
                ('owner', models.ForeignKey(help_text='Выберите автора', on_delete=django.db.models.deletion.CASCADE, to='authors.authors', verbose_name='books_owner')),
            ],
        ),
    ]
